plot(medv ~ lstat, data=Boston)
fit1 <- lm(medv ~ lstat, data=Boston)
abline(fit1, col="red")
names(fit1)
confint(fit1)
predict(fit1, data.frame(lstat=c(5,10,15)
),interval="confidence")

fit2 <- lm(medv ~ lstat + age, data=Boston)
summary(fit2)
.5^12 *100

fit3 <- lm(medv ~ ., data=Boston)
summary(fit3)
par(mfrow=c(2,2))
plot(fit3)
fit4 <- update(fit3, ~.-age-indus)
summary(fit4)
fit5 <- lm(medv ~ lstat*age, Boston)
fit6 <- lm(medv ~ lstat + I(lstat^2), Boston); summary(fit6)
par(mfrow=c(1,1))
plot(Boston$lstat, Boston$medv)
points(Boston$lstat, fitted(fit6), col="red", pch=20)
fit7 <- lm(medv ~ poly(lstat, 4), data=Boston)
points(Boston$lstat, fitted(fit7), col="blue", pch=20)
plot(1:20, 1:20, pch=1:20)
data(Carseats)
fit1 <- lm(Sales ~. + Income:Advertising + Age:Price, Carseats)
summary(fit1)
contrasts(Carseats$ShelveLoc)

regplot <- function(x, y,...) {
    fit <- lm(y ~ x)
    plot(x, y,...)
    abline(fit, col="red")
}

regplot(Carseats$Price, Carseats$Sales, xlab="Price", ylab="Sales")
str(Boston)
library(magrittr)
library(dplyr)

Boston %>%
    group_by(rad) %>%
    summarise_each(funs(mean))

data(Auto)
fit <- lm(mpg ~ horsepower, data=Auto)
fit2 <- lm(mpg ~ horsepower + I(horsepower ^ 2), data=Auto)
summary(fit2)
confint(fit)
plot(Auto$horsepower, Auto$mpg)
abline(fit, col="red")
plot(fit)

pairs(Auto)
data(Auto)
cor(Auto)
glimpse(Auto)
Auto <- Auto[,-9]
cor(Auto)
fit3 <- lm(mpg ~., data=Auto)
summary(fit3)
plot(fit3)
fit4 <- lm(mpg ~ cylinders + weight + horsepower + year + horsepower*year, data=Auto)
summary(fit4)
fit5 <- lm(mpg ~ weight + horsepower + year + horsepower*year, data=Auto)
summary(fit5)

set.seed(1)
x <- rnorm(100)
y <- 2 * x + rnorm(100)
fit6 <- lm(y ~ x - 1)
summary(fit6)
((sqrt(100 - 1)) * (sum(x*y)))/(sqrt(sum(x^2) * sum(y^2) - (sum(x*y)^2)))
fit7 <- lm(x ~ y - 1)

set.seed(1)
x <- rnorm(100)
eps <- rnorm(100, sd=0.75)
y <- -1 + 0.5*x + eps
length(y)
plot(x,y)
fit7 <- lm(y ~ x)
summary(fit7)
abline(fit7, col="red")
polyfit <- lm(y ~ x + I(x^2))
summary(polyfit)

set.seed(1)
x1 <- runif(100)
x2 <- 0.5 * x1 + rnorm(100)/10
y <- 2 + 2*x1 + 0.3*x2 + rnorm(100)
fit8 <- lm(y ~ x1 + x2)
summary(fit8)
cor(x1, x2)
plot(x1, x2)
fit9 <- lm(y ~ x1)
summary(fit9)
summary(lm(y ~ x2))
x1 <- append(x1, 0.1)
x2 <- append(x2, 0.8)
y <- append(y,6)
summary(lm(y ~ x1 + x2))
length(x1)
summary(lm(y ~ x1))
